name: "Setup Credentials"

inputs:
  AWS_ACCESS_KEY_ID:
    required: true
    type: string
  AWS_SECRET_ACCESS_KEY:
    required: true
    type: string
  AWS_ROLE_TO_ASSUME:
    required: true
    type: string
  AWS_ROLE_EXTERNAL_ID:
    required: true
    type: string

outputs:
  CODE_ARTIFACT_TOKEN:
    value: ${{ steps.codeartifact.outputs.token }}
  DOCKER_REGISTRY_USER:
    value: ${{ steps.login-ecr.outputs.docker_username_719468614044_dkr_ecr_us_west_2_amazonaws_com }}
  DOCKER_REGISTRY_PASSWORD:
    value: ${{ steps.login-ecr.outputs.docker_password_719468614044_dkr_ecr_us_west_2_amazonaws_com }}

runs:
  using: "composite"
  steps:
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-west-2
      role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
      role-external-id: ${{ inputs.AWS_ROLE_EXTERNAL_ID }}
      role-skip-session-tagging: true
  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v2
  - name: Login to AWS CodeArtifact
    id: codeartifact
    shell: bash
    run: |
      token=$(aws codeartifact get-authorization-token --domain-owner 719468614044 --domain kognitos --query 'authorizationToken' --output text)
      echo "::add-mask::$token"
      echo "token=$token" >> $GITHUB_OUTPUT
