name: "Git Lint"

runs:
  using: "composite"
  steps:
  - name: Lint commits
    uses: aschbacd/gitlint-action@v1.2.0
    with:
      re-commit-message-split: "^([^\n]*)(?:\n+([\s\S]*[^\n]))?\n*$"
      re-commit-message-subject: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([\w\-\.]+\))?(!)?: ((?:[\w ])+)"
      re-commit-message-body: "(?:\n+((?:[^#\n]+\n*?)+))??(?:\n+((?:[A-Z][a-z](?:-[a-z]+): (?:[A-Za-z]+ )+<[\w\-\.]+@(?:[\w\-]+\.)+[\w\-]{2,4}>)(?:\n+[A-Z][a-z](?:-[a-z]+): (?:[A-Za-z]+ )+<[\w\-\.]+@(?:[\w\-]+\.)+[\w\-]{2,4}>)))?(?:\n+((?:#.*\n*?)+))?\n*$"
      re-tag-name: "^v?\d+\.\d+\.\d+$"