#!/usr/bin/env python

import re

## Conventional commits

error_message = "The commit message format must be a conventional commit (https://www.conventionalcommits.org/en/v1.0.0/)"
pattern = r"^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)"

with open("./.git/HEAD") as f:
    branch = f.read().removeprefix("ref: ").strip()

with open("./.git/COMMIT_EDITMSG") as f:
    message = f.read()

if branch == 'refs/heads/master' or branch == 'refs/heads/main':
    if not re.match(pattern, message):
        raise Exception(error_message)