name: "Setup Configuration Variables"

on:
  workflow_call:
    inputs:
      CONFIG_FILE_PATH:
        required: false
        type: string
        default: "./book-config.yaml"

env:
  TEST: "TESTVAL"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.list }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - shell: bash
        run: pip install pyyaml toml
      - shell: bash
        id: matrix
        run: python ./.github/scripts/setup.py ${{ inputs.CONFIG_FILE_PATH }}

  output:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.matrix) }}
    outputs:
      ${{ matrix.value }}_result: ${{ steps.matrix_output.outputs.JOB_STATUS }}
    steps:
    - shell: bash
      id: matrix_output
      run: |
          echo "Matrix.val=\"${{ matrix.value }}\"" >> $GITHUB_OUTPUT
          echo "SECONDENV=123123123" >> $GITHUB_ENV



