name: "Setup Configuration Variables"

on:
  workflow_call:
    inputs:
      CONFIG_FILE_PATH:
        required: false
        type: string
        default: "./book-config.yaml"

    outputs: 
      out:
        value: ${{ jobs.setup.outputs }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ toJSON(steps.matrix.outputs) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - shell: bash
        run: pip install pyyaml toml
      - shell: bash
        id: matrix
        run: python ./.github/scripts/setup.py ${{ inputs.CONFIG_FILE_PATH }}

  # output:
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   strategy:
  #     matrix:
  #       value: ${{ fromJSON(needs.setup.outputs.matrix) }}
  #   steps:
  #   - shell: bash
  #     run: |
  #         echo "${{ matrix.value }}"



