name: "Setup Configuration Variables"

on:
  workflow_call:
    inputs:
      CONFIG_FILE_PATH:
        required: false
        type: string
        default: "./book-config.yaml"
    
    outputs:
      BOOK_NAME:
        value: ${{ steps.vars.outputs.BOOK_NAME }}
      AWS_ACCOUNT_ID:
        value: ${{ steps.vars.outputs.AWS_ACCOUNT_ID }}
      AWS_REGION:
        value: ${{ steps.vars.outputs.AWS_REGION }}
      DOCKER_REGISTRY:
        value: ${{ steps.vars.outputs.DOCKER_REGISTRY }}
      TERRAFORM_BACKEND_BUCKET_NAME:
        value: ${{ steps.vars.outputs.TERRAFORM_BACKEND_BUCKET_NAME }}

jobs:
  LoadVariables:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.list }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - shell: bash
        run: pip install pyyaml toml
      - shell: bash
        id: vars
        run: python ./.github/scripts/setup.py ${{ inputs.CONFIG_FILE_PATH }}



