name: Semantic Release and Terraform Deploy

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string

jobs:
  SemanticRelease:
    runs-on: ubuntu-latest
    needs: CheckAndTestCode
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
    - name: Setup Credentials
      uses: ./.github/actions/setup_credentials
      id: setup_credentials
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        AWS_ROLE_EXTERNAL_ID: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
    - name: Semantic Release Docker Image
      id: semantic
      uses: cycjimmy/semantic-release-action@v4
      with:
        branches: |
          main
        extra_plugins: |
          @codedependant/semantic-release-docker
      env:
        CODE_ARTIFACT_TOKEN: ${{ steps.setup_credentials.outputs.CODE_ARTIFACT_TOKEN }}
        DOCKER_REGISTRY_USER: ${{ steps.setup_credentials.outputs.DOCKER_REGISTRY_USER }}
        DOCKER_REGISTRY_PASSWORD: ${{ steps.setup_credentials.outputs.DOCKER_REGISTRY_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        DOCKER_PROJECT: ${{ env.PROJECT_NAME }}
        DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}

    - name: Terraform Deploy
      uses: ./.github/actions/terraform
      if: steps.semantic.outputs.new_release_published == 'true'
      with:
        MAJOR_VERSION: ${{ steps.semantic.outputs.new_release_major_version }}
        MINOR_VERSION: ${{ steps.semantic.outputs.new_release_minor_version }}
        PATCH_VERSION: ${{ steps.semantic.outputs.new_release_patch_version }}
        PROJECT_NAME: ${{ env.PROJECT_NAME }}
        BOOK_NAME: ${{ env.BOOK_NAME }}
        DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}
